apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: scalable-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: backend:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: db.scalable-app.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 3000
